### PR TITLE
Browser

### PR DESCRIPTION
**Pull request by kzidane**
cc @dmalan @glennholloway

### CODE REVIEW

**Comment by dmalan** [comment]
@kzidane have a screenshot handy of what the latest phpLiteAdmin UX looks like?

**Comment by kzidane** [comment]
With the current harvard.cs50.simple/master:
master

This opens if student clicks on the URL in the terminal and selects **Open in Preview**. Of course we can avoid "Could not execute browser" by commenting out the browser command again, for now.

With harvard.cs50.simple/browser/preview:
browser_preview

preview tab opens automatically. If the user runs phpliteadmin on same or other db, it's loaded in the same tab. If C9 are good with the title tweaks (or add their own), it should be possible to set the title of the tab to something like "phpliteadmin" or "phpliteadmin foo.db", and the following wouldn't happen after refresh, for non-active preview tabs:

after-refresh

**Comment by kzidane** [comment]
PS, if we're okay with not having control over titles, we can merge in the other features (browser commend, UI simplification, etc), for now?

**Comment by kzidane** [comment]
@dmalan @glennholloway I disabled `c9 exec browser` for now. Seems like we'd have to [implement](https://github.com/c9/c9.ide.preview.browser/pull/3#issuecomment-289511022) our own preview editor and/or built-in browser somehow. I'll look into how best to implement this, and demo asap. In the meantime, we should probably push 1.2.1 to fix the offline URL [glitch](https://www.facebook.com/groups/cs50/permalink/867124476767932/?comment_id=867595343387512&comment_tracking=%7B%22tn%22%3A%22R%22%7D)? Been there for a while now.

**Comment by dmalan** [comment]
:shipit:

**Comment by kzidane** [comment]
Rebased!

**Comment by dmalan** [comment]
:shipit:

**Pull request merged**
